FROM node:20
WORKDIR /app

COPY package.json .

RUN npm install


ENV DATABASE_URL="postgresql://postgres:postgres@postrgressql1:5432/postgres?schema=public"

COPY . .

COPY init.sh .

RUN chmod +x init.sh

ENTRYPOINT ["/app/init.sh"]