# Use an official Nginx image as the base image
FROM nginx:latest

# Copy your custom Nginx configuration file into the image
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to the outside world
EXPOSE 8080

# Command to run Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]